server:
  port: 8083
  servlet:
   context-path:  /communalf
spring:
        profiles:
           active:   communal, ${env}



#jwt configuration
jwt:
  header:  Authorization
  secret:  mySecret
  #token有效期一天
  expiration:  86400
  authHeader:   authorities
  tokenHeader:  accessToken
  tokenPrefix:    Bearer
  antMatchers:    /security/noauth






